#- name: Creates directory
#  file:
#    path: /home/ubuntu/backend
#    state: directory

- name: Transfer Zipped file
  copy:
    src: /root/project/backend.tgz
    dest: /home/ubuntu/

- name: Untar file
  shell: |
    cd /home/ubuntu
    tar -xvzf backend.tgz

#unarchive: src=/home/ubuntu/backend.tgz dest=/home/ubuntu

#- name: Transfer backend files cloud server
#  copy:
#    src: /root/project/backend
#    dest: /home/ubuntu/

- name: "Curl nvm"
  become: true
  shell: |
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash

- name: "Install latest node and npm"
  become: true
  shell: |
    cd /home/ubuntu/backend   
    source ~/.bashrc
    nvm install 16

- name: "Use latest npm to install dependencies"
  become: true
  shell: |
    nvm use 16
    npm install
  # npm audit fix --audit-level=critical --force
  # ls -la

- name: "build package"
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm run build

- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
    pm2 ls
#--------------------------------------------
#- name: Stop PM2
#  ignore_errors: yes
#  shell: |
#    sudo pm2 stop backend
#    sudo pm2 delete backend

#- name: Build node service
#  shell: |
#    cd /home/ubuntu/backend
#    sudo npm i
#    sudo npm audit fix --audit-level=critical --force
#    sudo npm run build
      
#- name: Start pm2 service
#  shell: |
#    cd /home/ubuntu/backend
#    sudo pm2 start npm --name backend -- start 
#    ls /home/ubuntu/.pm2/logs